# Site
#repository: sproogen/resume-theme
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 오석준
title: Embedded Engineer
email: osj982@naver.com
website: www.github.com/seokjun982

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  seokjun982
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  안녕하세요! 임베디드 개발자가 되고싶은 오석준입니다.
  대학 시절 여러 프로젝트를 수행하면서 개발자로서의 역량을 키울 수 있었습니다. 
  특히 임베디드 시스템 수업에서 센서와 모듈을 활용하여 다양한 서비스를 구현하는 과정은 저에게 임베디드 개발자로의 진로를 결정하게 해 준 중요한 경험이었습니다.
  대학을 졸업한 후에는 실무에서 사용되는 다양한 임베디드 보드에 대한 개발 경험을 쌓기 위해 대한상공회의소 서울기술교육센터에서 자율형 IoT 기반 Reality AI 융합 전문가 과정을 수료하고있습니다. 
  교육과정에서는 ARM Cortex-M3/M4, Udoo, Raspberry Pi, Jetson nano 등 다양한 임베디드 보드에 대한 경험을 쌓을 수 있었으며, 디바이스 드라이버 개발 및 펌웨어 개발,
  ROS, OpenCV를 이용한 자율주행 로봇 프로젝트를 진행하였습니다.
  저의 모토는 나의 위치에서 내가 해야 할 일을 성실하고 꾸준하게 책임감 있게 행동하는 것입니다.
  이러한 경험들을 바탕으로 회사와 동반성장 하고싶습니다. 
 
 

  I am most skilled in: <mark>C++</mark> and <mark>C</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: my project
        link: github.com/seokjun982
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
        
        quote: >
          I have organized the materials and projects that I have studied and worked on so far into a GitHub repository.
        description: | # this will include new lines to allow paragraphs
          I started using <mark>GitHub<mark> to study and organize my knowledge of C and C++ programming languages, but it has since allowed me to learn many new skills and build up my portfolio.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Redtable Company
        link: https://company.redtable.global/main/
        # link_text: boringcompany.com
        sub_title: Intern Data Preprocessing   
        caption: August 2022 - November 2022
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: 
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hallym University
        caption: 2015 - 2022
        sub_title: Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: 
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
